spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: false

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace